-- Lycoris 阶段 0 数据结构基线（仅结构，无数据）
--
-- 用途：空测试库 lycoris_rust 的建表结构参考，供 Rust 后端集成测试初始化。
-- 来源：生产库 PostgreSQL 17.8 的 pg_dump 纯结构导出，已移除 \restrict/\unrestrict、
--       SET 指令与生成注释，仅保留表、列类型、identity 序列、默认值、主外键与唯一约束。
-- 限制：本文件不是对已有生产库重复执行的迁移，只用于空库初始化；不含测试或真实用户数据。
--       仅创建 PostGIS 扩展；其余扩展不创建。所有对象归属执行本文件的角色。
-- 注意：users 的 username/email 在生产结构中无唯一约束（与 Java 实体一致），
--       本基线不擅自添加约束；差异记录见 docs/rust-migration/versions.md。

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE public.map_marker_translations (
    id bigint NOT NULL,
    marker_id bigint NOT NULL,
    language character varying(2) NOT NULL,
    title character varying(120) NOT NULL,
    description text,
    source_hash character varying(64) NOT NULL,
    origin character varying(16) DEFAULT 'MACHINE'::character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.map_marker_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.map_marker_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.map_markers (
    id bigint NOT NULL,
    category character varying(64) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description text,
    is_active boolean NOT NULL,
    is_public boolean NOT NULL,
    last_edited_by character varying(64),
    last_edited_by_owner boolean NOT NULL,
    last_edited_by_public_id character varying(64),
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    mark_image character varying(512),
    open_time_end character varying(5),
    open_time_start character varying(5),
    review_status character varying(16) NOT NULL,
    title character varying(120) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_public_id character varying(64),
    username character varying(64) NOT NULL,
    client_request_id character varying(64),
    version bigint DEFAULT 0 NOT NULL,
    source_language character varying(2) DEFAULT 'zh'::character varying NOT NULL
);

ALTER TABLE public.map_markers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.map_markers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.marker_edit_proposals (
    id bigint NOT NULL,
    category character varying(64) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description text,
    is_active boolean NOT NULL,
    is_public boolean NOT NULL,
    marker_id bigint NOT NULL,
    marker_lat double precision NOT NULL,
    marker_lng double precision NOT NULL,
    marker_title character varying(120) NOT NULL,
    open_time_end character varying(5),
    open_time_start character varying(5),
    proposer_is_owner boolean NOT NULL,
    proposer_public_id character varying(64),
    proposer_username character varying(64) NOT NULL,
    reviewed_at timestamp(6) with time zone,
    reviewed_by character varying(64),
    status character varying(16) NOT NULL,
    title character varying(120) NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    base_marker_version bigint,
    language character varying(2) DEFAULT 'zh'::character varying NOT NULL
);

ALTER TABLE public.marker_edit_proposals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marker_edit_proposals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.marker_favorites (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    marker_id bigint NOT NULL,
    user_public_id character varying(64) NOT NULL
);

ALTER TABLE public.marker_favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marker_favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.marker_image_proposals (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    image_url character varying(512) NOT NULL,
    marker_id bigint NOT NULL,
    marker_title character varying(120) NOT NULL,
    proposer_public_id character varying(64),
    proposer_username character varying(64) NOT NULL,
    reviewed_at timestamp(6) with time zone,
    reviewed_by character varying(64),
    status character varying(16) NOT NULL
);

ALTER TABLE public.marker_image_proposals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marker_image_proposals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id integer NOT NULL,
    avatar_url character varying(255),
    email character varying(255),
    nickname character varying(255),
    password character varying(255),
    pronouns character varying(64),
    public_id uuid NOT NULL,
    role character varying(32) NOT NULL,
    signature character varying(200),
    username character varying(255),
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp(6) with time zone,
    session_version bigint DEFAULT 0 NOT NULL,
    row_version bigint DEFAULT 0 NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.map_marker_translations
    ADD CONSTRAINT map_marker_translations_pkey PRIMARY KEY (id);

ALTER TABLE public.map_markers
    ADD CONSTRAINT map_markers_pkey PRIMARY KEY (id);

ALTER TABLE public.marker_edit_proposals
    ADD CONSTRAINT marker_edit_proposals_pkey PRIMARY KEY (id);

ALTER TABLE public.marker_favorites
    ADD CONSTRAINT marker_favorites_pkey PRIMARY KEY (id);

ALTER TABLE public.marker_image_proposals
    ADD CONSTRAINT marker_image_proposals_pkey PRIMARY KEY (id);

ALTER TABLE public.map_marker_translations
    ADD CONSTRAINT uk_map_marker_translation_language UNIQUE (marker_id, language);

ALTER TABLE public.map_markers
    ADD CONSTRAINT uk_map_markers_user_client_request UNIQUE (user_public_id, client_request_id);

ALTER TABLE public.users
    ADD CONSTRAINT uks24bux761rbgowsl7a4b386ba UNIQUE (public_id);

ALTER TABLE public.marker_favorites
    ADD CONSTRAINT uq_marker_fav_user_marker UNIQUE (user_public_id, marker_id);

ALTER TABLE public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE public.map_marker_translations
    ADD CONSTRAINT map_marker_translations_marker_id_fkey
    FOREIGN KEY (marker_id) REFERENCES public.map_markers(id) ON DELETE CASCADE;
