import { useUi } from '@/shared/i18n/ui'
const messages = {
    'Secondary verification is not configured on this server.': '此服务器尚未配置管理二次验证。',
    'Active flag': '有效标记',
    Yes: '是',
    No: '否',
    'Original content shown because this translation is unavailable.': '此语言暂无译文，显示原文。',
    Pages: '分页',
    'Check the title and both opening times.': '请检查标题及开放和关闭时间。',
    'This saves the changes as approved content.': '修改将保存为已审核通过的内容。',
    'Restore this account?': '恢复此账号？',
    Administration: '管理',
    'Back to map': '返回地图',
    Review: '审核',
    'All places': '全部点位',
    Users: '用户',
    Markers: '点位',
    Edits: '文字提案',
    Images: '图片提案',
    'Secondary verification': '二次验证',
    'Admin passcode': '管理密码',
    Verify: '验证',
    'Access denied.': '此账号没有管理权限。',
    'Could not confirm access. Try again.': '无法确认权限，请重试。',
    'Verification failed. Check the passcode and try again.': '验证失败，请检查管理密码后重试。',
    Approve: '通过',
    Reject: '拒绝',
    Delete: '删除',
    Edit: '编辑',
    Cancel: '取消',
    Confirm: '确认',
    Refresh: '刷新',
    Previous: '上一页',
    Next: '下一页',
    'No items.': '暂无内容。',
    'Search users': '搜索用户',
    Disable: '停用',
    Restore: '恢复',
    'Reset password': '重置密码',
    Disabled: '已停用',
    Active: '正常',
    Admin: '管理员',
    User: '用户',
    'Completed.': '操作已完成。',
    'The item changed. Review the refreshed list.': '内容已变化，请查看刷新后的列表。',
    'The outcome could not be confirmed. Refresh and inspect the item before trying again.':
        '无法确认操作结果，请刷新并检查条目后再决定是否重试。',
    'The request failed. Refresh and try again.': '请求失败，请刷新后重试。',
    'This action permanently deletes the place.': '这会永久删除该点位。',
    'This disables the account and invalidates its sessions.': '这会停用账号并使其登录会话失效。',
    'This resets the password to the server-configured default and invalidates existing sessions.':
        '这会将密码重置为服务器配置的默认值，并使现有登录会话失效。',
    'Clean missing images': '清理失效图片',
    'This removes references to missing image files.': '这会移除指向不存在图片的引用。',
    'Proposed changes': '提议的修改',
    'Current place': '当前点位',
    'Submitted by': '提交者',
    Visibility: '可见性',
    Language: '语言',
    Location: '位置',
    Submitted: '提交时间',
    'Edit approved content': '修改并通过内容',
    'Review status': '审核状态',
    'Image unavailable.': '图片暂不可用。',
    'Checking access…': '正在确认权限…',
} as const
export function useAdminUi() {
    const ui = useUi()
    return {
        ...ui,
        message: (value: string) =>
            ui.language === 'zh' && Object.hasOwn(messages, value)
                ? messages[value as keyof typeof messages]
                : ui.message(value),
    }
}
