import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { Slot } from 'radix-ui'
import { cn } from '@/shared/lib/cn'

/**
 * Generated by the official shadcn registry (`pnpm dlx shadcn@4.21.0 add button`)
 * from `src/shared/ui/button.tsx`, then adjusted to the project's Lycoris design
 * tokens: import paths, semantic colours from `--ui-*`, and the Figma control
 * radius/height (control 44px, radius 22px) instead of the registry defaults.
 */
const buttonVariants = cva(
    "inline-flex shrink-0 items-center justify-center gap-2 whitespace-nowrap transition-all outline-none focus-visible:ring-[3px] focus-visible:ring-(--ui-brand-blush) disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
    {
        variants: {
            variant: {
                figma: '',
                default: 'bg-(--ui-brand-deep) text-(--ui-on-brand) hover:bg-(--ui-brand-deep)/90',
                outline:
                    'border border-(--ui-brand-deep)/30 bg-transparent text-(--ui-brand-deep) hover:bg-(--ui-selected)',
                ghost: 'text-(--ui-brand-deep) hover:bg-(--ui-selected)',
                link: 'text-(--ui-brand-deep) underline-offset-4 hover:underline',
            },
            size: {
                figma: '',
                default: 'h-(--ui-control-height) rounded-(--ui-control-radius) px-5 text-base',
                sm: 'h-9 rounded-(--ui-control-radius) px-4 text-sm',
                lg: 'h-12 rounded-(--ui-control-radius) px-6 text-base',
                icon: 'size-(--ui-control-height) rounded-full',
            },
        },
        defaultVariants: {
            variant: 'default',
            size: 'default',
        },
    },
)

function Button({
    className,
    variant = 'default',
    size = 'default',
    asChild = false,
    ...props
}: React.ComponentProps<'button'> &
    VariantProps<typeof buttonVariants> & {
        asChild?: boolean
    }) {
    const Comp = asChild ? Slot.Root : 'button'

    return (
        <Comp
            data-slot="button"
            data-variant={variant}
            data-size={size}
            className={cn(buttonVariants({ variant, size, className }))}
            {...props}
        />
    )
}

export { Button, buttonVariants }
