-- Additive PostgreSQL migration. Existing marker text remains unchanged.
BEGIN;

ALTER TABLE map_markers
    ADD COLUMN IF NOT EXISTS source_language varchar(2) NOT NULL DEFAULT 'zh';
ALTER TABLE marker_edit_proposals
    ADD COLUMN IF NOT EXISTS language varchar(2) NOT NULL DEFAULT 'zh';

CREATE TABLE IF NOT EXISTS map_marker_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marker_id bigint NOT NULL REFERENCES map_markers(id) ON DELETE CASCADE,
    language varchar(2) NOT NULL,
    title varchar(120) NOT NULL,
    description text,
    source_hash varchar(64) NOT NULL,
    origin varchar(16) NOT NULL DEFAULT 'MACHINE',
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_map_marker_translation_language UNIQUE (marker_id, language)
);

COMMIT;
